### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by siddhanthaldar** [siddhanthaldar/CUDA-CNN-Traffic-Sign-Recognition#1]
## Things to do
- [x]  Class for convolution layers
- [x]  Class for fully connected layers
- [x]  Classes for activation functions(ReLU, Sigmoid, etc.)
- [x]  Class for dropout
- [x]  Class for pooling
- [x]  GPU kernel for gray level transformation
- [x]  GPU kernel for localized histogram equalization
- [x]  Initial training on GTSRB Dataset
- [x]  Develop ReadMe
